#!/bin/bash

#PBS -q sm
#PBS -N run_rjmcmc
#PBS -l select=1:ncpus=28:ompthreads=28
#PBS -l walltime=180:00:00

# Connect to project directory in imaging folder
cd /storage2/unipd/vanderbeek/cascadia_rjmcmc

# Run Julia code (note 3 arguments passed)
OPTS=' -O3 --check-bounds=no'
echo "start ---- $(date +%Y%m%d_%H%M%S)"
julia $OPTS run_rjMCMC.jl cas_iso_ref_20km 28 1 # (project name, number of chains, number of chunks)
echo "stop ----- $(date +%Y%m%d_%H%M%S)"
