#!/bin/bash

# Job Options #

#PBS -q sm
#PBS -N ani_benchmark
#PBS -l select=1:ncpus=28:ompthreads=28
#PBS -l walltime=180:00:00

# Required Environment Variables #

export PSI_S=/storage2/unipd/vanderbeek/PSI_S
export TAUP_JAR=/u/unipd/vanderbeek/TauP_Toolkit/TauP-2.7.0-SNAPSHOT5/lib/TauP-2.7.0-SNAPSHOT5.jar

# Require Variables #

WRKDIR=/storage2/unipd/vanderbeek/cascadia_rjmcmc/P # From where the job will run
PARFILE=parameters.toml # PSI_S parameter file
NCHAINS=28 # Number of chains to run in parallel
ICHUNK=1 # Chunk number for this simulation
JFILE=call_psi_s.jl # Julia file to run
OPTS=--check-bounds=no # Julia flags

# Run Job #

cd $WRKDIR
julia $OPTS $JFILE $PARFILE $NCHAINS $ICHUNK
