#!/bin/bash

# Job Options #

#PBS -q sm
#PBS -N ensemble
#PBS -l select=1:ncpus=28:ompthreads=28
#PBS -l walltime=180:00:00

# Required Environment Variables #

export PSI_S=/storage2/unipd/vanderbeek/PSI_S

# Require Variables #

WRKDIR=/storage2/unipd/vanderbeek/cascadia_rjmcmc/P # From where the job will run
JFILE=make_ensemble_vts.jl # Julia file to run
OPTS=--check-bounds=no # Julia flags

# Run Job #
cd $WRKDIR
julia $OPTS $JFILE
