#!/bin/bash

#PBS -q sm
#PBS -N run_merge_chains
#PBS -l select=1:ncpus=28:ompthreads=1
#PBS -l walltime=120:00:00

# Connect to project directory in imaging folder
cd /storage2/unipd/vanderbeek/cascadia_rjmcmc

# Run Julia code (note 3 arguments passed)
OPTS=' -O3 --check-bounds=no'
echo "start ---- $(date +%Y%m%d_%H%M%S)"
julia $OPTS merge_chains.jl cas_iso_ref_20km 28 50 # (project name, number of chains, burn-in index)
echo "stop ----- $(date +%Y%m%d_%H%M%S)"
